### PR TITLE
CSS for ATM designed by @Risengan

### PR DESCRIPTION
**Pull request by ElNelyo**

### CODE REVIEW

**Comment by ElNelyo** [comment]
Not sure about the files , test it before

**Comment by RomainLanz** [comment]
Hey @ElNelyo !

Maybe you can provide a screen of the result? 😄

**Comment by ElNelyo** [comment]
unknown

Sure ! ;)

**Comment by MisterMike99** [comment]
why for me its like this?? :/
https://gyazo.com/953071cb19a827830ed8118481ecd1d4

**Comment by ElNelyo** [comment]
I'll correct it tonight

**Pull request closed without merging**
